In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Superstore_Sales.xls')

In [3]:
df = df[['Customer ID','Sub-Category']]

In [4]:
df

     Customer ID Sub-Category
0       CG-12520    Bookcases
1       CG-12520       Chairs
2       DV-13045       Labels
3       SO-20335       Tables
4       SO-20335      Storage
...          ...          ...
9989    TB-21400  Furnishings
9990    DB-13060  Furnishings
9991    DB-13060       Phones
9992    DB-13060        Paper
9993    CC-12220   Appliances

[9994 rows x 2 columns]

In [5]:
group1 = df.groupby(['Customer ID','Sub-Category']).size().unstack()
group1

Sub-Category,Accessories,Appliances,Art,Binders,Bookcases,Chairs,Copiers,Envelopes,Fasteners,Furnishings,Labels,Machines,Paper,Phones,Storage,Supplies,Tables
Customer ID,,,,,,,,,,,,,,,,,
AA-10315,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN
AA-10375,2.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,4.0,1.0,2.0,NaN,NaN
AA-10480,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,5.0,1.0,2.0,NaN,1.0
AA-10645,NaN,NaN,1.0,1.0,1.0,3.0,NaN,1.0,NaN,4.0,NaN,NaN,2.0,2.0,3.0,NaN,NaN
AB-10015,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XP-21865,3.0,2.0,4.0,4.0,NaN,NaN,NaN,1.0,1.0,4.0,NaN,NaN,7.0,NaN,2.0,NaN,NaN
YC-21895,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,2.0,1.0,2.0,NaN,NaN
YS-21880,1.0,NaN,1.0,2.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,4.0,NaN,1.0
ZC-21910,4.0,3.0,3.0,4.0,NaN,3.0,NaN,2.0,1.0,3.0,NaN,NaN,3.0,2.0,1.0,NaN,2.0
ZD-21925,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN

In [6]:
group1 = group1.fillna(0)

In [7]:
group1.columns

Index(['Accessories', 'Appliances', 'Art', 'Binders', 'Bookcases', 'Chairs',
       'Copiers', 'Envelopes', 'Fasteners', 'Furnishings', 'Labels',
       'Machines', 'Paper', 'Phones', 'Storage', 'Supplies', 'Tables'],
      dtype='object', name='Sub-Category')

In [8]:
group2 = group1.values.astype('bool').astype('int')
group2 = pd.DataFrame(group2, columns = group1.columns, index = group1.index)

In [9]:
group2

Sub-Category,Accessories,Appliances,Art,Binders,Bookcases,Chairs,Copiers,Envelopes,Fasteners,Furnishings,Labels,Machines,Paper,Phones,Storage,Supplies,Tables
Customer ID,,,,,,,,,,,,,,,,,
AA-10315,1,1,0,1,0,0,0,0,1,1,0,0,1,1,1,1,0
AA-10375,1,0,1,1,0,0,0,0,0,1,0,0,1,1,1,0,0
AA-10480,1,0,1,0,0,0,0,0,0,1,0,0,1,1,1,0,1
AA-10645,0,0,1,1,1,1,0,1,0,1,0,0,1,1,1,0,0
AB-10015,0,0,1,0,1,1,0,0,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XP-21865,1,1,1,1,0,0,0,1,1,1,0,0,1,0,1,0,0
YC-21895,0,0,1,0,0,0,1,0,0,1,0,0,1,1,1,0,0
YS-21880,1,0,1,1,0,1,0,1,0,1,0,0,0,0,1,0,1
ZC-21910,1,1,1,1,0,1,0,1,1,1,0,0,1,1,1,0,1
ZD-21925,0,1,1,1,0,0,0,0,0,1,0,0,1,1,0,0,0

In [10]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [11]:
frequent_itemsets = apriori(group2, min_support=0.2, use_colnames=True)
frequent_itemsets

      support                                        itemsets
0    0.597730                                   (Accessories)
1    0.448928                                    (Appliances)
2    0.622951                                           (Art)
3    0.819672                                       (Binders)
4    0.245902                                     (Bookcases)
..        ...                                             ...
229  0.232030     (Furnishings, Binders, Paper, Art, Storage)
230  0.200504    (Furnishings, Phones, Binders, Art, Storage)
231  0.229508          (Phones, Binders, Paper, Art, Storage)
232  0.201765   (Furnishings, Chairs, Phones, Binders, Paper)
233  0.243380  (Furnishings, Phones, Binders, Paper, Storage)

[234 rows x 2 columns]

In [12]:
frequent_itemsets.sort_values(['support'],ascending=[0])

      support                                       itemsets
3    0.819672                                      (Binders)
10   0.770492                                        (Paper)
8    0.665826                                  (Furnishings)
46   0.650694                               (Binders, Paper)
12   0.648172                                      (Storage)
..        ...                                            ...
232  0.201765  (Furnishings, Chairs, Phones, Binders, Paper)
13   0.201765                                     (Supplies)
143  0.200504                     (Storage, Binders, Tables)
50   0.200504                             (Bookcases, Paper)
230  0.200504   (Furnishings, Phones, Binders, Art, Storage)

[234 rows x 2 columns]

In [13]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Accessories),(Appliances),0.597730,0.448928,0.274905,0.459916,1.024475,0.006568,1.020344
1,(Appliances),(Accessories),0.448928,0.597730,0.274905,0.612360,1.024475,0.006568,1.037740
2,(Accessories),(Art),0.597730,0.622951,0.404792,0.677215,1.087109,0.032435,1.168113
3,(Art),(Accessories),0.622951,0.597730,0.404792,0.649798,1.087109,0.032435,1.148678
4,(Binders),(Accessories),0.819672,0.597730,0.508197,0.620000,1.037257,0.018254,1.058605
...,...,...,...,...,...,...,...,...,...
1891,(Furnishings),"(Phones, Paper, Storage, Binders)",0.665826,0.317781,0.243380,0.365530,1.150260,0.031793,1.075259
1892,(Phones),"(Binders, Paper, Furnishings, Storage)",0.644388,0.330391,0.243380,0.377691,1.143163,0.030479,1.076007
1893,(Binders),"(Phones, Paper, Furnishings, Storage)",0.819672,0.279950,0.243380,0.296923,1.060631,0.013913,1.024142
1894,(Paper),"(Phones, Furnishings, Storage, Binders)",0.770492,0.272383,0.243380,0.315876,1.159673,0.033510,1.063574
1895,(Storage),"(Phones, Paper, Furnishings, Binders)",0.648172,0.316520,0.243380,0.375486,1.186298,0.038221,1.094420

In [14]:
rules[(rules.confidence >= 0.8)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
5,(Accessories),(Binders),0.597730,0.819672,0.508197,0.850211,1.037257,0.018254,1.203879
13,(Accessories),(Paper),0.597730,0.770492,0.491803,0.822785,1.067870,0.031257,1.295082
23,(Appliances),(Binders),0.448928,0.819672,0.392182,0.873596,1.065787,0.024208,1.426594
29,(Appliances),(Paper),0.448928,0.770492,0.359395,0.800562,1.039027,0.013499,1.150773
35,(Art),(Binders),0.622951,0.819672,0.523329,0.840081,1.024899,0.012714,1.127620
...,...,...,...,...,...,...,...,...,...
1809,"(Phones, Paper, Storage, Art)",(Binders),0.257251,0.819672,0.229508,0.892157,1.088431,0.018647,1.672131
1836,"(Binders, Phones, Furnishings, Chairs)",(Paper),0.225725,0.770492,0.201765,0.893855,1.160109,0.027846,2.162209
1837,"(Phones, Paper, Furnishings, Chairs)",(Binders),0.230769,0.819672,0.201765,0.874317,1.066667,0.012610,1.434783
1867,"(Phones, Furnishings, Storage, Binders)",(Paper),0.272383,0.770492,0.243380,0.893519,1.159673,0.033510,2.155381
1868,"(Phones, Paper, Furnishings, Storage)",(Binders),0.279950,0.819672,0.243380,0.869369,1.060631,0.013913,1.380441